from typing import Final

BUILD_AGENT_SUCCESSFUL: Final[str] = "BUILD_AGENT SUCCESSFUL"
BUILD_AGENT_FAILED: Final[str] = "BUILD_AGENT FAILED"
TEST_AGENT_SUCCESSFUL: Final[str] = "TEST_AGENT SUCCESSFUL"
TEST_AGENT_FAILED: Final[str] = "TEST_AGENT FAILED"
SCAFFOLD_AGENT_DONE: Final[str] = "SCAFFOLD_AGENT DONE"
