import io
import os
import sys
import textwrap
from contextlib import redirect_stdout

import pytest

from tests.test_utils import setup_test
from utils.config import Config
from utils.constants import BUILD_AGENT_SUCCESSFUL, TEST_AGENT_SUCCESSFUL
from utils.misc import to_os_path
from utils.tee import Tee
from workflows.new_app.new_app_workflow import NewAppWorkflow

SKIP_TESTS = False

prompt_cs_two_layer_greeting_app = textwrap.dedent(
    """
    Write a C# console app that writes a random greeting to the console.
    
    Use .NET 8.
    
    The app should have a UI layer and a backend layer. The UI should get the greeting message from the backend and display it to the user.
    
    Create a new solution MyGreetingApp.sln and add two projects to it as follows:
    - MyGreetingApp.UI
    - MyGreetingApp.Backend
    
    The backend should have 20 different greeting and the should return randomly one of them
    """
)

prompt_cs_fi_ssn_validator_lib = textwrap.dedent(
    """
    Your task is to create a C# solution that provides a validator for Finnish Social Security Numbers (SSN).
    
    Create a solution MyBase.FiSsnValidator and add the following projects to the solution:
    
    - MyBase.FiSsnValidator: contains the validator implementation
    - MyBase.FiSsnValidator.Tests: contains the unit tests for the validator

    Common requirements:
    - Use .NET 8
    - Use xUnit for unit tests
    - Do not use mocking in the tests, use the real implementation of the validator
    - Do not use logging in the validator
    - Add "Generated by DevAgents" as a comment to the top of the code files
    - Remove unnecessary code files created by the project templ
    
    Generate unit tests with xUnit for the following test cases:
        "010101-123N": valid
        "010101A123P": not valid
        "290202-1234": not valid
        "301299-123Y": not valid
        "150500-123A": not valid
        "151200A123B": not valid
        "060400-123C": not valid
        "290200-123D": not valid
        "290299-123E": not valid
        "100100A123F": not valid
        "010198A123G": not valid
        "010399A123H": not valid
        "010101-123M": not valid
        "010101-123Z": not valid
        "010101-123W": not valid
        "310232-123K": not valid
        "010101-123X": not valid
        "010101-123Y": not valid
        "010101-123Q": not valid
        "010101-123R": not valid
        "130593-935K": valid
        "250757-969R": valid
        "090222-987X": valid
        "240332-943K": valid
        "210268-931R": valid
    """
)

prompt_java_fi_ssn_validator_console_app = textwrap.dedent(
    """
    Write a Java console app that validates Finnish Social Security Numbers (SSN).

    Name the app ssn-validator.

    Generate unit tests for the following test cases:
        "010101-123N": valid
        "010101A123P": not valid
        "290202-1234": not valid
        "301299-123Y": not valid
        "150500-123A": not valid
        "151200A123B": not valid
        "060400-123C": not valid
        "290200-123D": not valid
        "290299-123E": not valid
        "100100A123F": not valid
        "010198A123G": not valid
        "010399A123H": not valid
        "010101-123M": not valid
        "010101-123Z": not valid
        "010101-123W": not valid
        "310232-123K": not valid
        "010101-123X": not valid
        "010101-123Y": not valid
        "010101-123Q": not valid
        "010101-123R": not valid
        "130593-935K": valid
        "250757-969R": valid
        "090222-987X": valid
        "240332-943K": valid
        "210268-931R": valid
    """
)

prompt_react_weather_app = textwrap.dedent(
    """
    Create a React app that displays the current weather in a given city.
    The user should be able to enter a city name and get the current weather information.
    
    Use the OpenWeatherMap API to get the weather data (API key fa14cac89ac69ef69f67f55b7ecd1dbb).
    
    The app should be responsive and work on mobile devices.
    Design the user interface to be user-friendly and visually appealing.
    The user interface should also be accessible to users with disabilities.
    Use rounded corners and shadows to make the app look modern and clean.
    Use appropriate icons to show the weather information, e.g. sun, rain, snow, etc.
    
    Scaffold the app to the directory city-weather-now.
    Use the latest version of React and TypeScript.
    
    Write comprehensive tests for the app to confirm that it works as expected.
    
    Name the app as City Weather Now.
    Add a footer to the app with the following text: "Created by DevAgents".
    """
)


prompt_react_hello_world_app = textwrap.dedent(
    """
    Create a simple React app that displays "Hello World" and the current time.
    Scaffold the app using create-react-app and use TypeScript.
    Scaffold the app for Windows.
    Use the latest version of React and TypeScript.
    Use the working directory as the root of the app.
    Write also necessary tests for the app to confirm that it works as expected.
    Name the app HelloWorldFromReact.
    """
)


@pytest.mark.skipif(SKIP_TESTS, reason="Skipping test")
@pytest.mark.parametrize(
    "setup_test",
    [("new_app_workflow", "test_generate_cs_two_layer_greeting_app", None)],
    indirect=True,
)
@pytest.mark.asyncio
async def test_generate_cs_two_layer_greeting_app__creates_app(setup_test):
    # Arrange
    test_run_dir = setup_test
    workflow = NewAppWorkflow(config=Config())

    # Act
    await workflow.run_team(prompt=prompt_cs_two_layer_greeting_app)

    # Assert
    assert os.path.exists(
        os.path.join(test_run_dir, to_os_path("MyGreetingApp.UI\\bin\\Debug\\net8.0\\MyGreetingApp.UI.exe"))
    )
    assert os.path.exists(
        os.path.join(test_run_dir, to_os_path("MyGreetingApp.Backend\\bin\\Debug\\net8.0\\MyGreetingApp.Backend.dll"))
    )


@pytest.mark.skipif(SKIP_TESTS, reason="Skipping test")
@pytest.mark.parametrize(
    "setup_test",
    [("new_app_workflow", "test_generate_cs_fi_ssn_validator_lib", None)],
    indirect=True,
)
@pytest.mark.asyncio
async def test_generate_cs_fi_ssn_validator_lib__creates_lib(setup_test):
    # Arrange
    test_run_dir = setup_test
    workflow = NewAppWorkflow(config=Config())

    # Act
    await workflow.run_team(prompt=prompt_cs_fi_ssn_validator_lib)

    # Assert
    assert os.path.exists(
        os.path.join(test_run_dir, to_os_path("MyBase.FiSsnValidator\\bin\\Debug\\net8.0\\MyBase.FiSsnValidator.dll"))
    )
    assert os.path.exists(
        os.path.join(
            test_run_dir, to_os_path("MyBase.FiSsnValidator.Tests\\bin\\Debug\\net8.0\\MyBase.FiSsnValidator.Tests.dll")
        )
    )


@pytest.mark.skipif(SKIP_TESTS, reason="Skipping test")
@pytest.mark.parametrize(
    "setup_test",
    [("new_app_workflow", "test_generate_react_weather_app", None)],
    indirect=True,
)
@pytest.mark.asyncio
async def test_generate_react_weather_app__creates_app(setup_test):
    # Arrange
    test_run_dir = setup_test
    console_output = io.StringIO()
    tee = Tee(sys.stdout, console_output)
    workflow = NewAppWorkflow(config=Config())

    # Act
    with redirect_stdout(tee):
        await workflow.run_team(prompt=prompt_react_weather_app)
    output = console_output.getvalue()

    # Assert
    assert BUILD_AGENT_SUCCESSFUL in output, "Expected text not found in console output."
    assert TEST_AGENT_SUCCESSFUL in output, "Expected text not found in console output."


@pytest.mark.skipif(SKIP_TESTS, reason="Skipping test")
@pytest.mark.parametrize(
    "setup_test",
    [("new_app_workflow", "test_generate_react_hello_world_app", None)],
    indirect=True,
)
@pytest.mark.asyncio
async def test_generate_react_hello_world_app__creates_app(setup_test):
    # Arrange
    test_run_dir = setup_test
    console_output = io.StringIO()
    tee = Tee(sys.stdout, console_output)
    workflow = NewAppWorkflow(config=Config())

    # Act
    with redirect_stdout(tee):
        await workflow.run_team(prompt=prompt_react_hello_world_app)
    output = console_output.getvalue()

    # Assert
    assert BUILD_AGENT_SUCCESSFUL in output, "Expected text not found in console output."
    assert TEST_AGENT_SUCCESSFUL in output, "Expected text not found in console output."


@pytest.mark.skipif(SKIP_TESTS, reason="Skipping test")
@pytest.mark.parametrize(
    "setup_test",
    [("new_app_workflow", "test_generate_java_fi_ssn_validator_console_app", None)],
    indirect=True,
)
@pytest.mark.asyncio
async def test_generate_java_fi_ssn_validator_console_app__creates_app(setup_test):
    # Arrange
    test_run_dir = setup_test
    workflow = NewAppWorkflow(config=Config())

    # Act
    await workflow.run_team(prompt=prompt_java_fi_ssn_validator_console_app)

    # Assert
    assert os.path.exists(
        os.path.join(test_run_dir, to_os_path("ssn-validator\\target\\ssn-validator-1.0-SNAPSHOT.jar"))
    )
