import os
import textwrap

import pytest

from config import Config
from scenarios.new_app.new_app_scenario import NewAppScenario
from tests.test_utils import setup_test

SKIP_TESTS = False

prompt_cs_two_layer_greeting_app = textwrap.dedent(
    """
    Write a C# console app that writes a random greeting to the console.
    
    Use .NET 8.
    
    The app should have a UI layer and a backend layer. The UI should get the greeting message from the backend and display it to the user.
    
    Create a new solution MyGreetingApp.sln and add two projects to it as follows:
    - MyGreetingApp.UI
    - MyGreetingApp.Backend
    
    The backend should have 20 different greeting and the should return randomly one of them
    """
)

prompt_cs_fi_ssn_validator_lib = textwrap.dedent(
    """
    Your task is to create a C# solution that provides a validator for Finnish Social Security Numbers (SSN).
    
    Create a solution MyBase.FiSsnValidator and add the following projects to the solution:
    
    - MyBase.FiSsnValidator: contains the validator implementation
    - MyBase.FiSsnValidator.Tests: contains the unit tests for the validator

    Common requirements:
    - Use .NET 8
    - Use xUnit for unit tests
    - Do not use mocking in the tests, use the real implementation of the validator
    - Do not use logging in the validator
    - Add "Generated by DevAgents" as a comment to the top of the code files
    - Remove unnecessary code files created by the project templ
    
    Generate unit tests with xUnit for the following test cases:
        "010101-123N": valid
        "010101A123P": not valid
        "290202-1234": not valid
        "301299-123Y": not valid
        "150500-123A": not valid
        "151200A123B": not valid
        "060400-123C": not valid
        "290200-123D": not valid
        "290299-123E": not valid
        "100100A123F": not valid
        "010198A123G": not valid
        "010399A123H": not valid
        "010101-123M": not valid
        "010101-123Z": not valid
        "010101-123W": not valid
        "310232-123K": not valid
        "010101-123X": not valid
        "010101-123Y": not valid
        "010101-123Q": not valid
        "010101-123R": not valid
        "130593-935K": valid
        "250757-969R": valid
        "090222-987X": valid
        "240332-943K": valid
        "210268-931R": valid
    """
)


@pytest.mark.skipif(SKIP_TESTS, reason="Skipping test")
@pytest.mark.parametrize(
    "setup_test",
    [("new_app_scenario", "test_generate_cs_two_layer_greeting_app", None)],
    indirect=True,
)
@pytest.mark.asyncio
async def test_generate_cs_two_layer_greeting_app__creates_app(setup_test):
    # Arrange
    test_run_dir = setup_test
    scenario = NewAppScenario(config=Config())

    # Act
    await scenario.run_scenario(prompt=prompt_cs_two_layer_greeting_app)

    # Assert
    assert os.path.exists(os.path.join(test_run_dir, "MyGreetingApp.UI\\bin\\Debug\\net8.0\\MyGreetingApp.UI.exe"))
    assert os.path.exists(
        os.path.join(test_run_dir, "MyGreetingApp.Backend\\bin\\Debug\\net8.0\\MyGreetingApp.Backend.dll")
    )


@pytest.mark.skipif(SKIP_TESTS, reason="Skipping test")
@pytest.mark.parametrize(
    "setup_test",
    [("new_app_scenario", "test_generate_cs_fi_ssn_validator_lib", None)],
    indirect=True,
)
@pytest.mark.asyncio
async def test_generate_cs_fi_ssn_validator_lib__creates_app(setup_test):
    # Arrange
    test_run_dir = setup_test
    scenario = NewAppScenario(config=Config())

    # Act
    await scenario.run_scenario(prompt=prompt_cs_fi_ssn_validator_lib)

    # Assert
    assert os.path.exists(
        os.path.join(test_run_dir, "MyBase.FiSsnValidator\\bin\\Debug\\net8.0\\MyBase.FiSsnValidator.dll")
    )
    assert os.path.exists(
        os.path.join(test_run_dir, "MyBase.FiSsnValidator.Tests\\bin\\Debug\\net8.0\\MyBase.FiSsnValidator.Tests.dll")
    )
