from enum import Enum
from typing import Final

BUILD_AGENT_SUCCESSFUL: Final[str] = "BUILD_AGENT SUCCESSFUL"
BUILD_AGENT_FAILED: Final[str] = "BUILD_AGENT FAILED"
TEST_AGENT_SUCCESSFUL: Final[str] = "TEST_AGENT SUCCESSFUL"
TEST_AGENT_FAILED: Final[str] = "TEST_AGENT FAILED"
SCAFFOLD_AGENT_DONE: Final[str] = "SCAFFOLD_AGENT DONE"
DEVELOPER_AGENT_DONE: Final[str] = "DEVELOPER_AGENT DONE"


class ScenarioType(Enum):
    NEW_CODE = 200
    MODIFY_CODE = 300
    NEW_APP = 400
    MODIFY_APP = 500
    FIX_BUILD = 600
    FIX_TESTS = 700
